config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#home"
  get "about-us", to: 'pages#about', as: :about
  get 'history', to: 'pages#history'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 100 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def show
  end

  def index 
    @articles = Article.all
  end

  def new
    @article = Article.new
  end
  
  def edit
    @article = Article.find(params[:id])
  end
  
  def create
    @article = Article.new(params.require(:article).permit(:title, :description))
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      flash[:notice] = "Article could not be created."
      # redirect_to 'new'
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = 'Article was updated successfully'
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    if @article.destroy
      flash[:notice] = 'Article deleted successfully'
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    # flash.now[:notice] = 'Logged in successfully'
    # flash.now[:alert] = 'Invalid email or password'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<div class='container'>

 <div class='row justify-content-center'>
   <div class='col-10'>
    <%= render 'shared/errors'%>
    <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class='form-group row'>
            <%= f.label :title,  class: 'col-2 col-form-label text-white' %>
            <div class='col-10'>
            <%= f.text_field :title, class: 'form-control shadow rounded', placeholder:'Title of article' %>
            </div>
        </div>
        <div class='form-group row'>
          <%= f.label :description,  class: 'col-2 col-form-label text-white' %>
          <div class='col-10'>
          <%= f.text_area :description, rows:10, class: 'form-control shadow rounded', placeholder:'Description of article' %>
          </div>
        </div>

        <div class='form-group row justify-content-center'>
            <%= f.submit class: 'btn btn-outline-light btn-lg' %>
        </div>
    <% end %>
    <p class='text-center'>
        <%= link_to 'Cancel Return to articles listing', articles_path, class: 'text-info' %>
    </p>
    </div>
</div>
</div>

app/views/articles/edit.html.erb
<h1 class='text-center mb-5 pt-3'>Edit Article</h1>
<%= render 'form' %>
 <p>
   <%= link_to 'Cancel and return to articles listing', articles_path %>
</p>

app/views/articles/index.html.erb
<h1 class='text-center mb-5 pt-3'>Article listing page</h1>

    <div class='container d-flex flex-column'>
        <div class='row justify-content-md-center'>
            <% @articles.each do |article|%>
            <div class='col-8'>
                <div class="card text-center mb-3 shadow rounded bg-white">
                    <div class="card-header font-italic">
                        By Ezzywealth
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-success text-capitalize">
                        <%= link_to article.title, article_path(article), class: 'text-success'%>
                        </h5>
                        <p class="card-text"> <%= article.description %> </p>
                
                        <div class='d-flex justify-content-center'>
                            <%= link_to 'Show', article_path(article), class: 'btn btn-outline-info mr-2'%>
                            <%= link_to 'edit', edit_article_path(article), class: 'btn btn-outline-success mr-2'%>
                            <%= button_to 'delete', article_path(article), method: :delete, data:{turbo_confirm: 'Are you sure?'}, class: 'btn btn-outline-danger'%>
                        </div>
                    </div>
                    <div class="card-footer text-muted">
                       <small> Created <%= time_ago_in_words(article.created_at)%> ago, edited <%= time_ago_in_words(article.updated_at) %> ago   
                       </small>
                    </div>
                </div>
            </div>
            <% end %>
        </div>
    </div>
    


    <p>
    <%= link_to 'Create new Article', new_article_path %>
    </p>
    <p>
    <%= link_to 'Go Home',  %>
    </p>

app/views/articles/new.html.erb
<h1 class='text-center mb-5 pt-3'>Create new Article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<div class='container'>
<h1 class='text-center'>Showing article details</h1>
<div class='row justify-content-center'>
    <div class='col-8'>
        <div class="card text-center mb-3 shadow rounded bg-white">
            <div class="card-header font-italic">
                By Ezzywealth
            </div>
            <div class="card-body">
                <h5 class="card-title text-success text-capitalize">
                <%= link_to @article.title, article_path(@article), class: 'text-success'%>
                </h5>
                <p class="card-text"> <%= @article.description %> </p>
        
                <div class='d-flex justify-content-center'>
                    <%= link_to 'edit', edit_article_path(@article), class: 'btn btn-outline-success mr-2'%>
                    <%= button_to 'delete', article_path(@article), method: :delete, data:{turbo_confirm: 'Are you sure?'}, class: 'btn btn-outline-danger'%>
                </div>
            </div>
            <div class="card-footer text-muted">
                <small> Created <%= time_ago_in_words(@article.created_at)%> ago, edited <%= time_ago_in_words(@article.updated_at) %> ago   
                </small>
            </div>
        </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg|%>
     <div class="container alert alert-success alert-dismissible fade show" role="alert">     
        <%= msg %>
         <button type='button' class='close' data-dismiss='alert' aria-label='close'>
            <span aria-hidden='true'>&times;</span>
         </button>
      </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: 'shared/navbar' %>
    <div id='page-content'>
      <%= render partial: 'layouts/messages' %>
      <%= yield %>
      <%= render partial: 'shared/footer' %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h2 class='d-flex justify-content-center'>This is the about page</h2>

app/views/pages/history.html.erb
<h3>This is the history page</h3>

app/views/pages/home.html.erb
<div class='container pt-3'>
    <div class="jumbotron text-center text-light" style="background-image : url('https://images.unsplash.com/photo-1505682634904-d7c8d95cdc50?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80');  background-repeat: no-repeat; background-size: cover; min-height:100%; background-position:right">
    <h1 class="display-4">Hello, world!</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
    </div>
</div>

app/views/shared/_errors.html.erb
 <% if @article.errors.any? %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <h4 class="alert-heading">The following errors prevented the article from been saved</h4>
            <ul>
            <% @article.errors.full_messages.each do |msg|%>
            <li><%= msg %></li>
            <% end %>
            </ul>
            <button type='button' class='close' data-dismiss='alert' aria-label='close'>
              <span aria-hidden='true'>&times;</span>
            </button>
            </div>
    <% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice]%>
  <div class="alert alert-success" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert]%>
  <div class="alert alert-warning" role="alert">
    <%= flash[:alert]%>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='sticky-footer' class='py-4 bg-dark text-white'>
  <div class='container text-center'>
    <small>Copyright &copy; <%= link_to 'Ezekiel Udiomnuo', 'https://eudiomuno.vercel.app', class: 'text-white' %></small>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark text-light ">
      <%= link_to 'ALpha Blog', root_path, class:'navbar-brand', id:'logo' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
          <%= link_to 'About', about_path, class:'nav-link'%>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Articles
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Create new Article', new_article_path, class:"dropdown-item" %>
              <%= link_to 'View Articles', articles_path, class:"dropdown-item" %>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

     <p>

    </p>
    <p>

    </p>